### PR TITLE
Consolidate ObsidisianX.sln

### PR DESCRIPTION
**Pull request by aubergemediale**
...so that it is equal to Blockcore.sln plus the four Obsidian* assemblies.

### CODE REVIEW

**Comment by aubergemediale** [comment]
thanks to https://github.com/sondreb, the tests are now actually executing and show real results. Last test run was 53 minutes, which shows the integrations tests are running properly.

**Comment by dangershony** [comment]
Brilliant, let me have a review and I will push

**Comment by dangershony** [comment]
This is how it looks like now, very good 👍 
image

**Comment by aubergemediale** [comment]
yes, looks like Obsidian now! :-)

**Pull request merged**
