### PR TITLE
Implement halving

### PR DESCRIPTION
**Pull request by dangershony**
There will be 5 periods of halving every roughly 2 years or (262,800 blocks)

After that the coin reward will be 1 ODX indefinitely

### CODE REVIEW

**Comment by aubergemediale** [comment]
> After that the coin reward will be 1 ODX indefinitely
That's reasonable, but I would not do this, _for optical reasons_. I would just keep on halving forever, because we then can specify a max supply.

**Comment by aubergemediale** [comment]
otherwise, the code looks good!

I think we'll much earlier see the reward is too low, so I'd just go with eternal halving first, and if we soft/hard fork one day, we can still modify the reward.

**Comment by dangershony** [comment]
>I would just keep on halving forever  

yeah fine with me

**Comment by dangershony** [comment]
This is the current table of the halving
8 halvings = 12 years

```
0 = 50.00000000
1 = 25.00000000
2 = 12.50000000
3 = 6.25000000
4 = 3.12500000
5 = 1.56250000
6 = 0.78125000
7 = 0.39062500
8 = 0.19531250
9 = 0 - proposal?
```

**Pull request merged**
